Function types 번역
golangkorea/golang-spec pull request #113
Opened 2017-12-07 05:03 UTC by jhonghee

2017-12-07 07:47 UTC, dakeshi requested changes
- 번역 가이드라인 규칙 적용
- 번역 개선안 추천

2017-12-07 07:47 UTC, dakeshi commented on Types/function_types.md
> +# [함수 타입(Function types)](#function-types)
> 함수 타입

타입에 대한 번역 가이드 라인은 `function 타입` 으로 추가된 상태인데 수정해야할라나요. `string 타입` 처럼 `function 타입`이 코드로 표현되는 경우가 있다면 `function 타입`을 적용하고 아니면 `함수 타입`이 좋을 것 같습니다.

2017-12-07 07:47 UTC, dakeshi commented on Types/function_types.md
> +함수 타입은 동일한 매개변수와 반환 타입을 지닌 모든 함수의 집합을 의미한다. 함수 타입의 초기화되지 않은 변수의 값은 `nil`이다.
> 동일한

[맞춤법 검사기](http://speller.cs.pusan.ac.kr/PnuWebSpeller/lib/check.asp)에서는 `동일한` 대신 `같은` 을 추천하고 있습니다.

> 함수 타입의 초기화되지 않은 변수의 값은 `nil`이다.

초기화되지 않은 함수 타입의 변수는 `nil` 값을 갖는다.  라는 표현이 더 나을 것 같아요.  그리고 문장만 봐서는 이해가 바로 되지는 않네요. 참고할 만한 예제가 있을까요?

2017-12-07 07:47 UTC, dakeshi commented on Types/function_types.md
> +함수의 시그니처내 맨 마지막에 오는 매개 변수는 ...을 앞세운 타입을 가질 수도 있다. 이런 매개 변수를 갖고 있는 함수를 *가변성(variadic)*이라고 부르고 그 매개변수를 위해 0 보다 크거나 같은 수의 인자를 사용해서 호출할 수 있다.
> 함수의 시그니처내 맨 마지막에 오는 매개 변수는 ...을 앞세운 타입을 가질 수도 있다.

함수 시그니처의 마지막 매개변수는 타입 정보 앞에 `...`를 함께 사용할 수 있다. 

> 이런 매개 변수를 갖고 있는 함수를 *가변성(variadic)*이라고 부르고 그 매개변수를 위해 0 보다 크거나 같은 수의 인자를 사용해서 호출할 수 있다.

이런 매개 변수를 갖고 있는 함수를 *variadic*이라고 부르고, 함수 호출시 이 매개변수에 해당하는 인자가 여러 개일 수도 있고, 하나도 없을 수도 있다.

`가변성` 대신 variadic 은 영문 그대로 유지하는게 나을 것 같습니다.

2017-12-07 07:47 UTC, dakeshi commented on Types/function_types.md
> +매개 변수나 반환 값들의 리스트내에서, 명칭들(IdentifierList)은 모두 나타나 있던지 아니면 아예 없어야 한다. 만약 모두 있다면, 각 명칭들은 주어진 타입의 한 항목(매개변수 혹은 반환값)을 나타내고 시그니처(signature)내의 모든 비-[공백(blank)](/Declarations%20and%20scope/blank_identifier.
> 매개 변수나 반환 값들의 리스트내에서, 명칭들(IdentifierList)은 모두 나타나 있던지 아니면 아예 없어야 한다.

매개변수나 반환 값을 표기할 때, 명칭(IdentifierList)은 모두 제공하거나 모두 생략해야 한다.

> 만약 모두 있다면, 각 명칭들은 주어진 타입의 한 항목(매개변수 혹은 반환값)을 나타내고 시그니처(signature)내의 모든 비-[공백(blank)](/Declarations%20and%20scope/blank_identifier.html) 명칭들은 [독특해야](/Declarations%20and%20scope/uniqueness_of_identifiers.html) 한다.

명칭을 제공할 경우, 각 명칭은 특정 타입을 갖는 1 개의 항목(매개변수 또는 반환 값)을 나타내며, [blank identifier](/Declarations%20and%20scope/blank_identifier.html) 를 제외한 모든 명칭은 시그니처 내에서 [고유해야](/Declarations%20and%20scope/uniqueness_of_identifiers.html) 한다.

> 만약 모든 명칭이 부재인 경우는, 각 타입이 그 타입의 한 항목임을 나타낸다.

명칭을 생략한 경우, 나열된 각각의 타입이 해당 항목의 타입을 의미한다.

> 매개변수와 반환 값 리스트는 항상 괄호를 사용해서 묶어 주어야 한다. 예외로 명칭이 주어지지 않은 반환 값이 단 하나일 때 괄호를 생략해도 된다.

매개변수와 반환 값 목록은 항상 괄호를 사용해서 묶어주어야 한다. 단, 반환 값이 1 개이고, 이것이 명칭이 주어지지 않은 반환 값(unnamed result)인 경우는 괄호를 생략해도 된다.

2017-12-08 00:58 UTC, jhonghee commented on Types/function_types.md
> +함수 타입은 동일한 매개변수와 반환 타입을 지닌 모든 함수의 집합을 의미한다. 함수 타입의 초기화되지 않은 변수의 값은 `nil`이다.
https://play.golang.org/p/vy5M4rB6Qh

2017-12-08 01:05 UTC, jhonghee commented on Types/function_types.md
> +함수의 시그니처내 맨 마지막에 오는 매개 변수는 ...을 앞세운 타입을 가질 수도 있다. 이런 매개 변수를 갖고 있는 함수를 *가변성(variadic)*이라고 부르고 그 매개변수를 위해 0 보다 크거나 같은 수의 인자를 사용해서 호출할 수 있다.
대박! 완전히 새롭고 훨씬 나은 번역입니다. 브라보!

2017-12-08 01:33 UTC, dakeshi approved these changes

2017-12-08 01:41 UTC, merged