interface 타입 번역
golangkorea/golang-spec pull request #119
Opened 2017-12-08 06:33 UTC by jhonghee

Review 부탁합니다.

2017-12-11 08:06 UTC, dakeshi requested changes
번역 감사합니다. 👍  코멘트 참조하셔서 수정 부탁드립니다.

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +interface 타입은 *인터페이스*라고 불리는 [메서드 집합(method set)](/Types/method_sets.html)을 열거한다. interface 타입의 변수는 주어진 인터페이스의 확대집합(superset)에 해당하는 메서드 집합을 갖고 있는 어떠한 타입의 값이든 저장할 수 있다. 그러한 타입에 대해서는 *인터페이스를 구현*했다라고 말한다
> [메서드 집합(method set)](/Types/method_sets.html)을 열거한다.

`열거한다`도 괜찮지만 보통 enumerate 를 `열거한다`로 번역하기 때문에 의역해서 `메서드 집합을 정의한다`, 또는 `메서드 집합을 명시한다` 가 어떨까요?

>  interface 타입의 변수는 주어진 인터페이스의 확대집합(superset)에 해당하는 메서드 집합을 갖고 있는 어떠한 타입의 값이든 저장할 수 있다. 

주어진 인터페이스의 확대집합(superset)에 해당하는 메서드 집합을 갖고 있는 어떠한 타입의 값이든 interface 타입의 변수에 저장할 수 있다.

>  초기화 되지 않은 interface 타입은 `nil` 값을 갖는다.

초기화되지 않은 interface 타입의 변수는 `nil` 값을 갖는다.

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +(위에서 `T`는 `S1`일 수도 있고 `S2`일 수도 있다) `S1`과 `S2`는 보유하고 있거나 공유하고 있는 다른 메서드들에 관계없이 `File` 인터페이스를 구현한 것이다.
> `S1`과 `S2`는 보유하고 있거나 공유하고 있는 다른 메서드들에 관계없이 `File` 인터페이스를 구현한 것이다.


이들이 가지고 있거나 공유하고 있는 다른 메서드들과는 상관없이 `S1`과 `S2`는 `File` 인터페이스를 구현한 것이다.

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +한 타입은 가지고 있는 모든 메서드중 한 부분만을 포함하는 어떤 인터페이스도 구현한다. 그러므로 별개의 여러 인터페이스들도 구현 할 수 있다. 예를 들어, 모든 타입은 *empty interface*를 구현한다:
> 한 타입은 가지고 있는 모든 메서드중 한 부분만을 포함하는 어떤 인터페이스도 구현한다. 그러므로 별개의 여러 인터페이스들도 구현 할 수 있다. 예를 들어, 모든 타입은 *empty interface*를 구현한다:

타입은 다양한 인터페이스를 구현할 수 있다는 의미이고 모든 타입은 empty interface를 기본적으로 구현하고 있다는 의미로 해석되네요.

타입은 자신의 메서드에 인터페이스의 메서드를 포함시키는 방법을 통해 어떠한 인터페이스든지 구현할 수 있기 때문에 여러 인터페이스를 함께 구현하는 것도 가능하다. 예를 들어, 모든 타입은 *empty interface*를 구현하고 있다:

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +유사하게, `Locker`라는 인터페이스를 정의하기 위한 [타입 선언문](/Declarations%20and%20scope/type_declarations.html)내 열거되어 있는 인터페이스 사양을 보자.
`유사하게`는 문맥상 삭제하는게 좀 더 자연스러울 것 같습니다.  empty interface와 유사하게라는 의미로 보더라도 뒷문장과 연결이 부드럽지 않습니다.

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +만약 `S1`과 `S2`가 다음과 같은 메서드를 또 구현했다면
> 만약 `S1`과 `S2`가 다음과 같은 메서드를 또 구현했다면

만약 `S1`과 `S2`가 아래의 메서드도 구현했다면

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +이들은 `File` 인터페이스 뿐만 아니라 `Locker` 인터페이스도 구현한 것이 된다.
> 구현한 것이 된다.

`구현한 것이다` 가 좀 더 자연스러운 것 같습니다.

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +어떤 인터페이스 `T`는 메서드의 사양이 있어야 할 자리에 (경우에 따라서는 패키지 이름을 동반한) interface 타입 이름 `E`를 사용할 수도 있다. 이것은 인터페이스 `E`를 `T`안에 *임베딩*한 것이라고 부른다: 임베딩은 (엑스포트 여부에 상관없이) `E`의 모든 메서드를 인터페이스 `T`에 더한다.
> 어떤 인터페이스 `T`는 

`어떤` 은 삭제해도 좋을 듯.

> 이것은 인터페이스 `E`를 `T`안에 *임베딩*한 것이라고 부른다:

이것은 `T`안에 인터페이스 `E`를 *임베딩*한 것이라고 부른다:

> 임베딩은 (엑스포트 여부에 상관없이) `E`의 모든 메서드를 인터페이스 `T`에 더한다. 

`더한다` 대신 `추가한다`는 표현은 어떨까요?

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +	ReadWriter  // ReadWriter의 메서드를 더하는 것과 같음
> 더하는 것과 같음

추가한 것과 같음

2017-12-11 08:06 UTC, dakeshi commented on Types/interface_types.md
> +// 불법: Bad1은 Bad2을 이용해 임베딩할 수 없음
> Bad2을 

Bad2를

2017-12-12 00:14 UTC, jhonghee commented on Types/interface_types.md
> +유사하게, `Locker`라는 인터페이스를 정의하기 위한 [타입 선언문](/Declarations%20and%20scope/type_declarations.html)내 열거되어 있는 인터페이스 사양을 보자.
상위문단의 예를 드는 것처럼 보여서 일단 "비슷한 경우로,"라고 바꿔보겠습니다. 그래도 이상하면 삭제하도록 하죠.

2017-12-12 00:18 UTC, dakeshi commented on Types/interface_types.md
> +유사하게, `Locker`라는 인터페이스를 정의하기 위한 [타입 선언문](/Declarations%20and%20scope/type_declarations.html)내 열거되어 있는 인터페이스 사양을 보자.
네엡.

2017-12-12 00:23 UTC, jhonghee commented
@dakeshi 님이 제안하신 수정 내용을 업데이트 했습니다. "유사하게 => 비슷한 경우로"는 추가 Review 부탁합니다.

2017-12-12 01:00 UTC, dakeshi approved these changes

2017-12-12 01:00 UTC, merged

2018-04-04 08:29 UTC, dakeshi commented
https://www.transifex.com/golang-korea/go-specification/translate/#ko/types_interface_typesmd/130649801