Types/boolean_types.md 번역
golangkorea/golang-spec pull request #120
Opened 2017-12-09 07:29 UTC by HurSungYun

2017-12-09 18:25 UTC, jhonghee approved these changes

2017-12-11 07:04 UTC, dakeshi requested changes
- 스펙 문서 html code tag 확인사항 반영
\*불리언 타입\*으로 변경해야 합니다.

- 기타 번역문 개선

2017-12-11 07:04 UTC, dakeshi commented on Types/boolean_types.md
> +불리언 *타입*은 미리 선언된 상수인 `true`와 `false` 로 나타내어지는 Boolean 진리 집합을 나타낸다. 미리 선언된 불리언 타입은 `bool`로 나타낸다.
> 불리언 *타입*은 미리 선언된 상수인 `true`와 `false` 로 나타내어지는 Boolean 진리 집합을 나타낸다. 미리 선언된 불리언 타입은 `bool`로 나타낸다.

스펙문서 html code 태그가 잘못 표기된 곳이 있네요.

*불리언 타입*은 미리 선언된 상수인 `true`와 `false` 로 표현되는 Boolean 진리 집합을 나타낸다. 미리 선언된 불리언 타입은 `bool`이다.

2017-12-11 16:15 UTC, HurSungYun commented
말씀해주신 부분 수정하였습니다

2017-12-11 23:27 UTC, dakeshi approved these changes

2017-12-12 01:29 UTC, merged