Translation finished - Built-in func/allocation.md
golangkorea/golang-spec pull request #122
Opened 2017-12-11 05:05 UTC by superbmilkyway

2017-12-11 06:53 UTC, dakeshi requested changes
번역 감사합니다. 👍  코멘트 참고해서 몇 가지 수정부탁드립니다.

2017-12-11 06:53 UTC, dakeshi commented on Built-in functions/README.md
> +# [내장 함수(Built-in functions)](#Built-in_functions)
reference id 는 소문자로만 유지하며 언더바 대신 `-`를 사용합니다. built-in-functions

2017-12-11 06:53 UTC, dakeshi commented on Built-in functions/close.md
> +# [Close 함수(Close)](#Close)
reference id는 소문자로 유지합니다.

2017-12-11 06:53 UTC, dakeshi commented on Built-in functions/length_and_capacity.md
> +# [길이와 용량(Length and capacity)](#Length_and_capacity)
reference id는 소문자로 유지하고 space는 `-`로 대체합니다. 언더바는 금지되어 있습니다.

2017-12-11 06:53 UTC, dakeshi commented on Built-in functions/allocation.md
> +# [할당(Allocation)](#Allocation)
reference id는 소문자로 구성합니다.

2017-12-11 06:53 UTC, dakeshi commented on Built-in functions/allocation.md
> +내장 함수 `new`는 타입 T를 받고, 런타임 시점에 해당 타입 [변수](/Variables/)를 위한 저장 공간을 할당하고 해당 공간을 [가르키는](/Types/pointer_types.html) *T 타입의 값을 반환한다. 해당 변수는 [초기값](/Program initialization and execution/the_zero_value.html)
> 내장 함수 `new`는 타입 T를 받고, 런타임 시점에 해당 타입 [변수](/Variables/)를 위한 저장 공간을 할당하고 해당 공간을 [가르키는](/Types/pointer_types.html) *T 타입의 값을 반환한다.

스펙 문서 옮기는 과정에서 T, *T에 대한 html code 태그가 빠져있네요. markdown에서는 \`T\`로 표기합니다. 

내장 함수 `new`는 타입 `T`를 인자로 받고, 런타임 시점에 해당 타입의 [변수](/Variables/)를 위한 저장 공간을 할당하며, 이 변수를 [가리키는](/Types/pointer_types.html) `*T` 타입의 값을 반환한다.

> 해당 변수는 [초기값](/Program initialization and execution/the_zero_value.html)절에서 설명한 것처럼 초기화 된다.

아래처럼 의역을 하는 것이 더 자연스럽겠네요.

해당 변수는 초기화되며 변수 초기화와 관련해서는 [초기값](/Program initialization and execution/the_zero_value.html)절을 참조하라.

2017-12-11 06:53 UTC, dakeshi commented on Built-in functions/allocation.md
> +S 타입의 변수를 위한 저장 공간을 할당하고, 해당 변수를(a=0, b=0.0)으로 초기화 하고 해당 공간의 주소를 담고 있는 *S 타입의 값을 반환한다.
스펙 옮기는 과정에서 `S`, `a=0`, `b=0.0`, `*S`에 대한 html code 태그가 빠졌습니다. 추가바랍니다.

2017-12-12 00:46 UTC, superbmilkyway commented
죄송합니다. 좀 주의 깊게 가이드 라인을 살폈어야 되는데 컨플릭트나니까 그냥 제꺼 위주로 합치다 보니 이런 일이 발생했네요ㅠㅠ

2017-12-12 01:09 UTC, dakeshi commented
가이드라인이 중간에 몇 번 갱신되어서 그런 점도 있습니다. 앞으로도 꾸준한 번역 부탁드립니다.  👍

2017-12-12 01:15 UTC, dakeshi requested changes
추가 수정 부탁드립니다.

2017-12-12 01:15 UTC, dakeshi commented on Built-in functions/README.md
> +# [내장 함수(Built-in functions)](#nuilt-in-functions)
> nuilt-in-functions

built-in-functions

2017-12-12 01:15 UTC, dakeshi commented on Built-in functions/allocation.md
> +내장 함수 `new`는 타입 `T`를 받고, 런타임 시점에 해당 타입 [변수](/Variables/)를 위한 저장 공간을 할당하고 해당 공간을 [가르키는](/Types/pointer_types.html) `*T` 타입의 값을 반환한다. 해당 변수는 초기화되며 변수 초기화와 관련해서는 [초기값](/Program initialization and execut
> 해당 공간을 [가르키는]

가리키는

2017-12-12 01:15 UTC, dakeshi commented on Built-in functions/allocation.md
> +`S` 타입의 변수를 위한 저장 공간을 할당하고, 해당 변수를(`a=0, b=0.0`)으로 초기화 하고 해당 공간의 주소를 담고 있는 `*S` 타입의 값을 반환한다.
> `a=0, b=0.0`

\`a=0\`, \`b=0.0\`

2017-12-12 05:52 UTC, jhonghee approved these changes

2017-12-18 20:30 UTC, jhonghee commented on Built-in functions/README.md
> +# [내장 함수(Built-in functions)](#nuilt-in-functions)
👍

2017-12-27 05:13 UTC, jhonghee approved these changes

2017-12-27 05:13 UTC, merged