Comparison operators
golangkorea/golang-spec pull request #128
Opened 2017-12-12 04:06 UTC by jhonghee

### 체크리스트
- [✔] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 
- [✔] 용어집에 추가할 번역 용어가 있나요? 있다면 [이슈 게시판](https://github.com/golangkorea/golang-spec/issues/105)에 코멘트를 남겨주세요.

### 설명

Comparison operators 번역

### 참고사항(선택사항)

2017-12-13 11:29 UTC, dakeshi requested changes
몇 가지는 토론할 부분이 보이네요.
comparison expression 챕터에서 많은 도움 받았습니다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> +비교 연산자들은 2개의 피 연산자들을 비교한 다음 미지정 타입의(untyped) 불리언 값을 생산한다.
> 비교 연산자들은 2개의 피 연산자들을 비교한 다음 미지정 타입의(untyped) 불리언 값을 생산한다.

비교 연산자에서 피연산자 2개를 비교한 결과는 미지정 타입의(untyped) 불리언 값으로 제공된다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> +>=    더 크거나 같은
```
같은 - 같다
같지 않은 - 같지 않다 또는 같지 않음
더 적은 - 작다
더 적거나 같은 - 작거나 같다 또는 작거나 같음
더 큰 - 크다
더 크거나 같은 - 크거나 같다 또는 크거나 같음
```

`적다` - `많다` 또는 `크다` - `작다` 로 통일된 표현을 사용하는 게 좋을 듯 합니다. less and greater 는 직역하자면 `많고 적음`이지만 연산자로 사용했을때 `이 숫자가 다른 숫자보다 크다, 작다` 처럼 말하는 경우가 일반적이므로 `크다, 작다`로 통일하는 것이 좋을 것 같습니다.

참고 [C# 연산자](https://docs.microsoft.com/ko-kr/dotnet/csharp/programming-guide/statements-expressions-operators/operators)

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> +*서로 비교할 수 있는* 피연산자들에 대등 연산자인 `==`와 `!=`가 적용된다. 순서 연산자인 `<`, `<=`, `>`, 그리고 `>=`는 *순서를 정할 수 있는* 피연산자들에 적용된다. 비교의 조건들과 결과에 대해서는 다음과 같이 정의한다:
> *서로 비교할 수 있는* 피연산자들에 대등 연산자인 `==`와 `!=`가 적용된다.

용어집 : 동등 연산자 

동등 연산자인 `==`와 `!=`의 피연산자들은 *서로 비교할 수(comparable)* 있어야 한다.

> 순서 연산자인 `<`, `<=`, `>`, 그리고 `>=`는 *순서를 정할 수 있는* 피연산자들에 적용된다.

ordering operator도 용어집에 추가해야 할 듯. 순서 연산자 또는 우선 순위 연산자가 적당할 거 같네요.

순서 연산자인 `<`, `<=`, `>`, `>=`의 피연산자들은 *확실하게 우선 순위가 구별될 수(ordered)* 있어야 한다.

> 비교의 조건들과 결과에 대해서는 다음과 같이 정의한다:

these terms는 comparable과 ordered를 말하는 것 같고 문장은 이들 용어가 아래 항목에서 사용되고 있다 정도로 해석할 수 있으므로 아래와 같이 번역할 수 있을 듯.

비교를 수행한 결과는 다음과 같다:

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> +	b5 MyBool = x == y // b5는 타입 MyBool를 갖는다
> b3는 타입 bool을 갖는다

타입 표현: string 타입, 불리언 타입으로 통일.

b3는 불리언 타입
b4는 불리언 타입
b5는 MyBool 타입

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> +슬라이스, map, 그리고 함수 값들은 비교할 수 없다. 하지만, 특별한 경우로, 하나의 슬라이스, map, 그리고 함수 값은 미리 선언된 식별자 `nil`과 비교할 수 있다. 포인터, 채널, 그리고 인터페이스 값을 `nil`과 비교하는 것도 허용되며 위에 명시된 일반적인 규칙을 따른다.
> 슬라이스, map, 그리고 함수 값들은 비교할 수 없다. 하지만, 특별한 경우로, 하나의 슬라이스, map, 그리고 함수 값은 미리 선언된 식별자 `nil`과 비교할 수 있다. 

그리고는 빼도 괜찮을 듯.

원칙적으로는 슬라이스, map, 함수 값들을 비교할 수 없지만,  미리 선언된 식별자 `nil`과는 비교할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 불리언 값들은 비교할 수 있다. 2개의 불리언 값은 둘 다 `true`이던지 `false`일 때 같다.
> 2개의 불리언 값은 둘 다 `true`이던지 `false`일 때 같다.

2개의 불리언 값이 모두 `true` 거나 `false`일때 *2개의 값이 같다*라고 말할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 정수 값들은, 잘 알려져 있듯이, 비교할 수 있고 순서도 있다.
> 정수 값들은, 잘 알려져 있듯이, 비교할 수 있고 순서도 있다.

정수 값들은 일반적으로 비교할 수 있으며 순서가 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 부동 소수점 값들은, IEEE-754 표준에 정의된 바에 따라, 비교할 수 있고 순서도 있다.
> 부동 소수점 값들은, IEEE-754 표준에 정의된 바에 따라, 비교할 수 있고 순서도 있다.

IEEE-754 표준에 따라 정의된 부동 소수점 값들은 비교할 수 있으며 순서가 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 복소수 값들은 비교 가능하다. 2개의 복소수 값들, `u`와 `v`는 만약 두 조건, `real(u) == real(v)`와 `imag(u) == imag(v)`가 만족하면 같다.
> 2개의 복소수 값들, `u`와 `v`는 만약 두 조건, `real(u) == real(v)`와 `imag(u) == imag(v)`가 만족하면 같다

2개의 복소수 값 `u`와 `v`는 `real(u) == real(v)`와 `imag(u) == imag(v)`를 동시에 만족할 경우 `서로 같다`라고 말할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * string 값들은 어휘적으로 바이트 단위로 비교할 수 있고 순서도 있다.
> string 값들은 어휘적으로 바이트 단위로 비교할 수 있고 순서도 있다.

lexically 는 논의가 필요할 듯.

문자열 값들은 어휘 바이트 단위로 비교할 수 있고 순서가 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 포인터 값들은 비교 가능하다. 2개의 포인터 값이 같은 변수를 가리키고 있던지 둘 다 `nil`이면 같다. 서로 다르며 [크기가 0인(zero-size)](/System%20considerations/size_and_alignment_guarantees.html) 변수들을 가리키는 포인터들은 같을 수도 있고 다를 수도 있다.
> 2개의 포인터 값이 같은 변수를 가리키고 있던지 둘 다 `nil`이면 같다. 서로 다르며 [크기가 0인(zero-size)]

zero-size도 논의가 필요할 듯.

2개의 포인터 값이 모두 `nil`이거나 같은 변수를 가리킬 때 `서로 같다`고 말할 수 있다. 서로 다른 zero-size 변수에 대한 포인터는 같거나 다를 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 채널 값들은 비교 가능하다. 만약 2개의 채널이 같은 [make](/making_slices,_maps_and_channels.html)의 호출을 통해 만들어 졌다면 같고, 둘 다 `nil`값을 갖고 있다면 같다.
> 만약 2개의 채널이 같은 [make](/making_slices,_maps_and_channels.html)의 호출을 통해 만들어 졌다면 같고, 둘 다 `nil`값을 갖고 있다면 같다.

만약 2개의 채널이 모두 `nil`값을 갖거나 같은 [make](/making_slices,_maps_and_channels.html)의 호출을 통해 만들어 졌다면 `같다`고 말할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 인터페이스 값들은 비교 가능하다. 2개의 인터페이스는 [동일한](/Properties%20of%20types%20and%20values/type_identity.html) 동적 타입을 가지고 있고 같은 동적 값을 가지고 있을 때 서로 같다. 둘 다 `nil`값을 갖고 있어도 같다.
> 2개의 인터페이스는 [동일한](/Properties%20of%20types%20and%20values/type_identity.html) 동적 타입을 가지고 있고 같은 동적 값을 가지고 있을 때 서로 같다. 둘 다 `nil`값을 갖고 있어도 같다.

2개의 인터페이스가 [같은(identical)](/Properties%20of%20types%20and%20values/type_identity.html) 동적 타입, 같은 동적 값을 가지고 있거나 둘 다 `nil`값을 갖고 있을 때 `같다`고 말할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 인터페이스가 아닌 타입 `X`의 값 `x`와 인터페이스 타입 `T`의 값 `t`는 `X`가 비교 가능한 타입이며 `T`를 구현하고 있는 경우 서로 비교할 수 있다.
> `X`가 비교 가능한 타입이며 `T`를 구현하고 있는 경우 서로 비교할 수 있다.

`X`가 비교 가능한 타입이며 `X`가 `T`를 구현하고 있는 경우 서로 비교할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * struct 값들은 필드가 모두 비교 가능한 경우에 비교연산에 사용할 수 있다. 2개의 struct 값들 사이에 [blank 식별자](/Declarations%20and%20scope/blank_identifier.html)가 아닌 상응하는 필드들이 서로 같은 값이면 같다.
> struct 값들은 필드가 모두 비교 가능한 경우에 비교연산에 사용할 수 있다

모든 필드가 비교 가능한 경우에 struct 값들을 비교할 수 있다.

> 2개의 struct 값들 사이에 [blank 식별자](/Declarations%20and%20scope/blank_identifier.html)가 아닌 상응하는 필드들이 서로 같은 값이면 같다.

2개의 struct 값들은 상응하는 필드([blank 식별자](/Declarations%20and%20scope/blank_identifier.html)가 아닌)가 같을 경우 `같다`고 말할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> + * 배열 값들은 만약 배열의 요소가 비교 가능한 타입이면 배열의 비교연산도 가능하다. 2개의 배열값 사이에는 만약 상응하는 요소들이 같다면 같다.
> 배열 값들은 만약 배열의 요소가 비교 가능한 타입이면 배열의 비교연산도 가능하다. 

배열 요소 타입의 값들이 비교 가능하면 배열 값들은 비교할 수 있다. 

> 2개의 배열값 사이에는 만약 상응하는 요소들이 같다면 같다.

상응하는 요소가 같다면 2개의 배열 값은 `같다`고 말할 수 있다.

2017-12-13 11:29 UTC, dakeshi commented on Expressions/comparison_operators.md
> +동일한 동적 타입을 갖는 2개의 인터페이스 값들이 비교했을 때 만약 이 값들이 비교 가능한 값들이 아니면 [런타임 패닉](/Run-time%20panics/)을 초래한다. 이러한 일들은 인터페이스간의 직접적인 비교뿐만 아니라 인터페이스 값을 지닌 배열을 비교할 때와 인터페이스 값을 갖고 있는 필드를 지닌 struct간의 비교에도 적용된다.
> 동일한 동적 타입을 갖는 2개의 인터페이스 값들이 비교했을 때 만약 이 값들이 비교 가능한 값들이 아니면 [런타임 패닉](/Run-time%20panics/)을 초래한다.

같은 동적 타입을 갖는 2개의 인터페이스 값들을 비교할 때, 동적 타입의 값을 비교할 수 없다면 [런타임 패닉](/Run-time%20panics/)이 발생한다.

> 이러한 일들은 인터페이스간의 직접적인 비교뿐만 아니라 인터페이스 값을 지닌 배열을 비교할 때와 인터페이스 값을 갖고 있는 필드를 지닌 struct간의 비교에도 적용된다.

이 규칙은 인터페이스간의 직접 비교뿐만 아니라 인터페이스 값을 지닌 배열 비교와 인터페이스 값을 갖고 있는 필드를 지닌 struct간의 비교에도 적용된다.

2017-12-14 00:44 UTC, jhonghee commented on Expressions/comparison_operators.md
> +비교 연산자들은 2개의 피 연산자들을 비교한 다음 미지정 타입의(untyped) 불리언 값을 생산한다.
수정해 주신 문장에서 비교 연산자를 주어로 써서

"비교 연산자로 피연산자 2개를 비교한 결과는 미지정 타입의(untyped) 불리언 값으로 제공된다."

2017-12-14 00:59 UTC, jhonghee commented on Expressions/comparison_operators.md
> +비교 연산자들은 2개의 피 연산자들을 비교한 다음 미지정 타입의(untyped) 불리언 값을 생산한다.
비교 연산자로 피연산자 2개를 비교한 결과는 미지정 타입의(untyped) 불리언 상수값으로 제공된다.

2017-12-14 01:27 UTC, jhonghee commented on Expressions/comparison_operators.md
> +*서로 비교할 수 있는* 피연산자들에 대등 연산자인 `==`와 `!=`가 적용된다. 순서 연산자인 `<`, `<=`, `>`, 그리고 `>=`는 *순서를 정할 수 있는* 피연산자들에 적용된다. 비교의 조건들과 결과에 대해서는 다음과 같이 정의한다:
비교항목에 대한 정의와 비교연산을 수행한 결과는 다음과 같다:

2017-12-14 02:13 UTC, merged