문 번역
golangkorea/golang-spec pull request #133
Opened 2017-12-13 10:04 UTC by ezaurum

### 체크리스트
- [ x] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 
- [ ] 용어집에 추가할 번역 용어가 있나요? 있다면 [이슈 게시판](https://github.com/golangkorea/golang-spec/issues/105)에 코멘트를 남겨주세요.

### 설명

문
### 참고사항(선택사항)

2017-12-14 00:41 UTC, jhonghee requested changes
Statement => 구문

2017-12-14 00:41 UTC, jhonghee commented on Statements/README.md
> +문은 실행을 관리한다.
statement는 구문으로 통일하면 좋겠습니다. 그것만 수정해 주시면 merge해도 되겠네요.

2017-12-14 01:07 UTC, dakeshi commented on Statements/README.md
> +문은 실행을 관리한다.
for statement 의 경우 for문, for 구문으로 번역할 수 있는데 for 문이라고 보통 말하니 문을 선택하는게 나을 것 같구요, statement만 별도로 언급할 때는 `구문`이라고 번역하는 것이 어감이 나을 것 같아요. 이 규칙을 적용하면 statement 섹션쪽은 for 문, if 문, ...defer 문이 챕터 제목이 되겠네요.

2017-12-14 09:09 UTC, ezaurum commented on Statements/README.md
> +문은 실행을 관리한다.
네 수정했습니다.

2017-12-17 15:07 UTC, dakeshi approved these changes

2017-12-17 15:08 UTC, merged