Translate struct_types
golangkorea/golang-spec pull request #138
Opened 2017-12-14 02:27 UTC by voidsatisfaction

### 체크리스트
- [x] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 
- [x] 용어집에 추가할 번역 용어가 있나요? 있다면 [이슈 게시판](https://github.com/golangkorea/golang-spec/issues/105)에 코멘트를 남겨주세요.

### 설명

struct_types

### 참고사항(선택사항)

2017-12-14 16:33 UTC, dakeshi requested changes
번역 감사드립니다. 👍  정리안된 내용들이 좀 있어서 리뷰에 상당한 시간이 소요되었습니다.

코멘트한 수정 사항들이 제대로 반영되지 않으면 내용을 다시 확인할 때도 상당한 시간이 소요될 것으로 판단됩니다.  따라서, 꼼꼼하게 수정사항 확인하셔서 PR 작성해주시길 부탁드립니다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +구조체는 필드(fields)의 연속이다. 필드는 이름과 타입을 갖고 있다. 필드의 이름은 명시적으로 지정되거나(IdentifierList) 암묵적으로 지정된다(임베드된 필드 EmbeddedField). 구조체 내부에는, non-[blank](/Declarations%20and%20scope/blank_identifier.html)인 필드 이름은 반드시 [
> 구조체는 필드(fields)의 연속이다. 필드는 이름과 타입을 갖고 있다.

sequence 번역은 한번 더 고민해봐야겠네요. tour of go에서는 struct 에 대해 다음과 같이 정의되어 있습니다. `A struct is a collection of fields.` 다른 챕터에서도 `연속`으로 번역했는데 `집합`, `그룹`의 의미로 번역하는게 맞을 듯. 일단은 `연속`으로 유지하겠습니다. 적당한 번역을 고민해보시죠. 추천 번역:

구조체는 이름과 타입으로 구성된 필드(field)의 연속이다. 

> 필드의 이름은 명시적으로 지정되거나(IdentifierList) 암묵적으로 지정된다(임베드된 필드 EmbeddedField).

EmbeddedField는 EBNF 문법을 그대로 사용한 것이므로 번역하지 않습니다.

필드 이름은 명시적(IdentifierList) 또는 암묵적(EmbeddedField)으로 표현할 수 있다.

> 구조체 내부에는, non-[blank](/Declarations%20and%20scope/blank_identifier.html)인 필드 이름은 반드시 [유일](/Declarations%20and%20scope/uniqueness_of_identifiers.html)해야한다.

[blank](/Declarations%20and%20scope/blank_identifier.html) 식별자를 제외한 구조체 내 모든 필드의 이름은 [고유](/Declarations%20and%20scope/uniqueness_of_identifiers.html)해야 한다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +// 빈 구조체.
다른 챕터에서는 empty interface, empty map 이란 표현을 영문 그대로 유지했으므로, empty struct 로 표현하는게 좋을 거 같습니다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +*임베드된 필드(embedded field)* 란 타입으로 선언되었으나 명시적인 이름이 없는 필드를 말한다. 임베드된 필드는 타입 이름 `T`로 지정되거나 인터페이스가 아닌 타입 이름 `*T`, 그리고 `T` 그자체가 포인터 타입이 아닐 수 있다. unqualified된 타입 이름이 필드 이름으로 될 수 있다.
> *임베드된 필드(embedded field)* 란 타입으로 선언되었으나 명시적인 이름이 없는 필드를 말한다.

명시적인 이름없이 타입만 선언된 필드를 *임베디드 필드(embedded field)*라고 한다.

> 임베드된 필드는 타입 이름 `T`로 지정되거나 인터페이스가 아닌 타입 이름 `*T`, 그리고 `T` 그자체가 포인터 타입이 아닐 수 있다. 

임베디드 필드는 타입 이름 `T` 또는 `*T`와 같은 포인터(인터페이스 타입에 대한 포인터는 사용할 수 없음)로 나타낼 수 있으며, `T`는 포인터 타입이 아니어야 한다. 

> unqualified된 타입 이름이 필드 이름으로 될 수 있다.

unqualified는 인터페이스 챕터에서도 논의되었지만, qualified identifier와 관련있는 내용이고, selectors 챕터를 읽어보니 이것이 selector expression을 의미하는 것일 수도 있겠네요. 
추가 논의가 필요할 듯. 일단 unqualified 로 유지합니다.

unqualified 타입 이름은 필드 이름처럼 사용된다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +// 타입 T1, *T2, P.T3, P.T4가 임베드된 4개의 필드를 가진 구조체
T1, *T2, P.T3 , *P.T 타입의 임베디드 필드 4개가 있는 구조체

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +	x, y int  // 필드 이름은 각각 x와 y
> 필드 이름은 각각 x와 y

필드 이름은 x, y

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +아래와 같은 선언은 구조체의 필드 이름이 반드시 유일해야 하기 때문에 허용되지 않는다:
> 아래와 같은 선언은 구조체의 필드 이름이 반드시 유일해야 하기 때문에 허용되지 않는다:

구조체의 필드 이름이 반드시 고유해야 하기 때문에 아래와 같은 선언문은 허용되지 않는다:

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +구조체 `x`에 임베드된 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html) `f`는 `x.f`가 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html)를 의미하는 유효한 [selector](/Expressions/selecto
> 구조체 `x`에 임베드된 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html) `f`는 `x.f`가 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html)를 의미하는 유효한 [selector](/Expressions/selectors.html)인 경우, 이를 *promoted* 라고 불린다.

promoted는 논의가 필요할 것 같고, 문장도 좀 더 고민해봐야 할 듯. 제안하는 번역은:

구조체 `x`에서 임베디드 필드의 필드 또는  [메서드](/Declarations%20and%20scope/method_declarations.html) `f`는 `x.f`에서 `f`가 유효한 [selector](/Expressions/selectors.html)인 경우 *promoted* 되었다고 말한다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +promoted 필드는 구조체의 [합성 리터럴](/Expressions/composite_literals.html)에서 필드 이름으로 사용 될 수 없는 것을 제외하고 일반적인 필드 처럼 행동한다.
> promoted 필드는 구조체의 [합성 리터럴](/Expressions/composite_literals.html)에서 필드 이름으로 사용 될 수 없는 것을 제외하고 일반적인 필드 처럼 행동한다.

promoted 필드는 구조체의 [합성 리터럴](/Expressions/composite_literals.html)에서 필드 이름으로 사용할 수 없는 경우를 제외하면 일반적인 구조체의 필드처럼 동작한다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +구조체 타입 `S`와 타입 이름 `T`가 주어졌을때, promoted 메서드는 아래와 같이 구조체의 메서드 집합(method set)에 포함된다:
> 구조체 타입 `S`와 타입 이름 `T`가 주어졌을때, promoted 메서드는 아래와 같이 구조체의 메서드 집합(method set)에 포함된다:

struct 타입이 `S`이고 임베디드 필드는 `T`일 때, promoted 메서드는 아래와 같이 구조체의 메서드 집합(method set)에 포함된다:

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +	T     // 임베드된 필드 *T, *P.T와 충돌
> 임베드된 필드

모든 주석을 다음과 같이 수정해주세요.

임베디드 필드

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `T`를 표함하면, `S`와 `*S`의 [메서드 집합](/Types/method_sets.html)은 receiver `T`와 함께 promoted 메서드를 포함한다. `*S`의 메서드 셋 역시 receiver `T`와 함께 promoted 메서드를 포함한다.
> 만약 `S`가 임베드된 필드 `T`를 표함하면, `S`와 `*S`의 [메서드 집합](/Types/method_sets.html)은 receiver `T`와 함께 promoted 메서드를 포함한다. `*S`의 메서드 셋 역시 receiver `T`와 함께 promoted 메서드를 포함한다.

`S`가 임베디드 필드 `T`를 포함하면, `S`의 [메서드 집합](/Types/method_sets.html)과 `*S`는 receiver를 `T`로 하는 promoted 메서드를 포함한다. 또한, `*S`의 메서드 집합은 receiver를 `*T`로 하는 promoted 메서드를 포함한다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `*T`를 포함하면, `S`와 `*S`의 메서드 집합은 receiver `T`,`*T`와 함께 promoted 메서드를 포함한다.
> 만약 `S`가 임베드된 필드 `*T`를 포함하면, `S`와 `*S`의 메서드 집합은 receiver `T`,`*T`와 함께 promoted 메서드를 포함한다.

`S`가 임베디드 필드 `*T`를 포함하면, `S`의 메서드 집합과 `*S`는 receiver를 `T`나 `*T`로 하는 promoted 메서드를 포함한다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +필드 선언에 문자열 리터럴 *태그* 를 선택적으로 놓을 수 있다. 그리고 그 태그는 해당하는 필드 선언의 모든 필드를 위한 속성이 된다. 공백의 태그 문자열은 태그가 없는 것과 같다. 태그들은 [reflection interface](https://golang.org/pkg/reflect/#StructTag)를 통해서 볼 수 있고, 구조체의 [타입 식별자
> 필드 선언에 문자열 리터럴 *태그* 를 선택적으로 놓을 수 있다. 그리고 그 태그는 해당하는 필드 선언의 모든 필드를 위한 속성이 된다. 

필드 선언시 문자열 리터럴 *태그* 를 덧붙일 수 있으며, 이것은 해당 필드의 선언문에서 필드의 속성이 된다.

> 공백의 태그 문자열은 태그가 없는 것과 같다.

공백은 space와 충돌하는 번역이므로 empty로 유지합니다. absent tag는 태그를 덧붙이지 않는 것과 동일한 뜻인지 확인이 필요할 것 같습니다. 일단, absent 태그로 유지합니다.

empty 태그 문자열은 absent 태그와 같다.

> 태그들은 [reflection interface](https://golang.org/pkg/reflect/#StructTag)를 통해서 볼 수 있고, 구조체의 [타입 식별자](/Properties%20of%20types%20and%20values/type_identity.html)에 참여하나 그렇지 않은 경우는 무시된다.

visible은 reflection interface를 이용해 tag 정보를 확인할 수 있다는 의미로 이해했습니다. type identity에 참여한다는 것은 type identity 구별에 tag 정보도 식별자로 사용된다는 의미로 보이네요.

태그들은 [reflection 인터페이스](https://golang.org/pkg/reflect/#StructTag)를 이용해 확인할 수 있으며, 구조체의 [타입 아이덴티티](/Properties%20of%20types%20and%20values/type_identity.html)를 판단할 때 영향을 준다. 그외의 경우에는 무시된다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +	x, y float64 ""  // 공백 태그 문자열은 태그가 없는 것과 같다.
> 공백 태그 문자열은 태그가 없는 것과 같다.

위에서 남긴 코멘트 참조. 

empty 태그 문자열은 absent 태그와 같다.

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +// TimeStamp protocol buffer와 대응하는 구조체.
> TimeStamp protocol buffer와 대응하는 구조체

`해당하는` 을 사용했지만 논의가 필요할 듯.

TimeStamp protocol buffer에 해당하는 구조체

2017-12-14 16:33 UTC, dakeshi commented on Types/struct_types.md
> +// reflect 패키지에 의해 구체화된 관습을 따른다.
> reflect 패키지에 의해 구체화된 관습을 따른다.

reflect 패키지에서 정한 관례를 따른다.

2017-12-14 19:12 UTC, jhonghee commented on Types/struct_types.md
> +구조체는 필드(fields)의 연속이다. 필드는 이름과 타입을 갖고 있다. 필드의 이름은 명시적으로 지정되거나(IdentifierList) 암묵적으로 지정된다(임베드된 필드 EmbeddedField). 구조체 내부에는, non-[blank](/Declarations%20and%20scope/blank_identifier.html)인 필드 이름은 반드시 [
+1 : 구조체는 이름과 타입으로 구성된 필드(field)의 연속이다.

+1: 필드 이름은 명시적(IdentifierList) 또는 암묵적(EmbeddedField)으로 표현할 수 있다.

+1: blank 식별자를 제외한 구조체 내 모든 필드의 이름은 고유해야 한다.

2017-12-14 19:13 UTC, jhonghee commented on Types/struct_types.md
> +// 빈 구조체.
@dakeshi 님 의견에 저도 동의합니다.

2017-12-14 19:20 UTC, jhonghee commented on Types/struct_types.md
> +*임베드된 필드(embedded field)* 란 타입으로 선언되었으나 명시적인 이름이 없는 필드를 말한다. 임베드된 필드는 타입 이름 `T`로 지정되거나 인터페이스가 아닌 타입 이름 `*T`, 그리고 `T` 그자체가 포인터 타입이 아닐 수 있다. unqualified된 타입 이름이 필드 이름으로 될 수 있다.
+1: 명시적인 이름없이 타입만 선언된 필드를 *임베디드 필드(embedded field)*라고 한다.

임베디드 필드는 타입 이름 T로 명시되거나 *T와 같이 포인터를 쓸때는 인터페이스 타입을 쓸 수 없다. 또한 T 자체는 포인터 타입이 아니어야 한다. unqualified 타입 이름은 필드 이름처럼 사용된다.

"unqualified 타입 이름은 필드 이름처럼 사용된다." 를 의역하면 "패키지이름을 동반하지 않은 unqualified 타입 이름이 필드 이름처럼 사용된다."

2017-12-14 19:20 UTC, jhonghee commented on Types/struct_types.md
> +// 타입 T1, *T2, P.T3, P.T4가 임베드된 4개의 필드를 가진 구조체
+1: T1, *T2, P.T3 , *P.T 타입의 임베디드 필드 4개가 있는 구조체

2017-12-14 19:21 UTC, jhonghee commented on Types/struct_types.md
> +아래와 같은 선언은 구조체의 필드 이름이 반드시 유일해야 하기 때문에 허용되지 않는다:
+1: 구조체의 필드 이름이 반드시 고유해야 하기 때문에 아래와 같은 선언문은 허용되지 않는다:

2017-12-14 19:47 UTC, jhonghee commented on Types/struct_types.md
> +구조체 `x`에 임베드된 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html) `f`는 `x.f`가 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html)를 의미하는 유효한 [selector](/Expressions/selecto
이런 경우를 말하는 것 같네요: https://play.golang.org/p/tDuftWphWO

x.f 가 selector로서 유효한 표현이면서, f 가 구조체 x의 임베디드 필드속 필드나 메서드일 경우에 승급(promoted)되었다고 한다.

2017-12-14 21:31 UTC, jhonghee commented on Types/struct_types.md
> +promoted 필드는 구조체의 [합성 리터럴](/Expressions/composite_literals.html)에서 필드 이름으로 사용 될 수 없는 것을 제외하고 일반적인 필드 처럼 행동한다.
+1 : promoted 필드는 구조체의 합성 리터럴에서 필드 이름으로 사용할 수 없는 경우를 제외하면 일반적인 구조체의 필드처럼 동작한다.

2017-12-14 22:03 UTC, jhonghee commented on Types/struct_types.md
> +구조체 타입 `S`와 타입 이름 `T`가 주어졌을때, promoted 메서드는 아래와 같이 구조체의 메서드 집합(method set)에 포함된다:
"struct 타입이 S이고 임베디드 필드는 T일 때" <- 이 부분은 임베디드 라는 설명을 빼는게 나은 것 같습니다.

"struct 타입이 S이고 T라는 이름의 한 타입이 주어졌을때, 그 구조체의 메서드 집합(method set)에 메서드가 승진되는(promoted) 경우는 다음과 같다."

2017-12-14 22:04 UTC, jhonghee commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `T`를 표함하면, `S`와 `*S`의 [메서드 집합](/Types/method_sets.html)은 receiver `T`와 함께 promoted 메서드를 포함한다. `*S`의 메서드 셋 역시 receiver `T`와 함께 promoted 메서드를 포함한다.
+1

2017-12-14 22:11 UTC, jhonghee commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `T`를 표함하면, `S`와 `*S`의 [메서드 집합](/Types/method_sets.html)은 receiver `T`와 함께 promoted 메서드를 포함한다. `*S`의 메서드 셋 역시 receiver `T`와 함께 promoted 메서드를 포함한다.
S가 임베디드 필드 T를 포함하면, S와 *S의 두 경우 모두 메서드 집합은 receiver를 T로 하는 promoted 메서드를 포함한다. 또한, *S의 메서드 집합은 receiver를 *T로 하는 promoted 메서드를 포함한다.

2017-12-14 22:12 UTC, jhonghee commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `*T`를 포함하면, `S`와 `*S`의 메서드 집합은 receiver `T`,`*T`와 함께 promoted 메서드를 포함한다.
S가 임베디드 필드 *T를 포함하면, S와 *S 두 경우 모두 메서드 집합은 receiver를 T나 *T로 하는 promoted 메서드를 포함한다.

2017-12-14 22:28 UTC, jhonghee commented on Types/struct_types.md
> +필드 선언에 문자열 리터럴 *태그* 를 선택적으로 놓을 수 있다. 그리고 그 태그는 해당하는 필드 선언의 모든 필드를 위한 속성이 된다. 공백의 태그 문자열은 태그가 없는 것과 같다. 태그들은 [reflection interface](https://golang.org/pkg/reflect/#StructTag)를 통해서 볼 수 있고, 구조체의 [타입 식별자
empty 태그 문자열은 absent 태그와 같다. => empty 문자열 태그은 태그의 부재를 의미한다.

2017-12-14 22:31 UTC, jhonghee commented on Types/struct_types.md
> +	x, y float64 ""  // 공백 태그 문자열은 태그가 없는 것과 같다.
이 경우도 "empty 태그 문자열은 태그가 없는 것과 같다." 나 "empty 태그 문자열은 태그가 부재라는 의미다." 로 번역하는게 나을 것 같습니다.

2017-12-14 22:38 UTC, jhonghee commented on Types/struct_types.md
> +// TimeStamp protocol buffer와 대응하는 구조체.
저도 "해당하는"이 적당한 번역이라고 봅니다.

2017-12-15 00:06 UTC, dakeshi commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `T`를 표함하면, `S`와 `*S`의 [메서드 집합](/Types/method_sets.html)은 receiver `T`와 함께 promoted 메서드를 포함한다. `*S`의 메서드 셋 역시 receiver `T`와 함께 promoted 메서드를 포함한다.
S와 *S 를 분리해서 해석했는데 @jhonghee 님 번역이 맞는거 같습니다.  💯

2017-12-15 00:34 UTC, voidsatisfaction commented
@dakeshi @jhonghee 두분 다 감사합니다. 수정 한 뒤에 풀리퀘스트 올릴게요.

2017-12-15 02:17 UTC, voidsatisfaction commented on Types/struct_types.md
> +구조체는 필드(fields)의 연속이다. 필드는 이름과 타입을 갖고 있다. 필드의 이름은 명시적으로 지정되거나(IdentifierList) 암묵적으로 지정된다(임베드된 필드 EmbeddedField). 구조체 내부에는, non-[blank](/Declarations%20and%20scope/blank_identifier.html)인 필드 이름은 반드시 [
수정했습니다.

2017-12-15 02:23 UTC, voidsatisfaction commented on Types/struct_types.md
> +*임베드된 필드(embedded field)* 란 타입으로 선언되었으나 명시적인 이름이 없는 필드를 말한다. 임베드된 필드는 타입 이름 `T`로 지정되거나 인터페이스가 아닌 타입 이름 `*T`, 그리고 `T` 그자체가 포인터 타입이 아닐 수 있다. unqualified된 타입 이름이 필드 이름으로 될 수 있다.
다른 문서에서 이미 `임베드`라는 단어를 써서 그대로 한건데 다른 문서도 고쳐야겠네요.

2017-12-15 02:24 UTC, voidsatisfaction commented on Types/struct_types.md
> +// 빈 구조체.
수정 했습니다.

2017-12-15 02:28 UTC, voidsatisfaction commented on Types/struct_types.md
> +*임베드된 필드(embedded field)* 란 타입으로 선언되었으나 명시적인 이름이 없는 필드를 말한다. 임베드된 필드는 타입 이름 `T`로 지정되거나 인터페이스가 아닌 타입 이름 `*T`, 그리고 `T` 그자체가 포인터 타입이 아닐 수 있다. unqualified된 타입 이름이 필드 이름으로 될 수 있다.
수정했습니다.

2017-12-15 02:30 UTC, voidsatisfaction commented on Types/struct_types.md
> +	x, y int  // 필드 이름은 각각 x와 y
수정했습니다

2017-12-15 02:30 UTC, voidsatisfaction commented on Types/struct_types.md
> +// 타입 T1, *T2, P.T3, P.T4가 임베드된 4개의 필드를 가진 구조체
수정했습니다

2017-12-15 02:30 UTC, voidsatisfaction commented on Types/struct_types.md
> +아래와 같은 선언은 구조체의 필드 이름이 반드시 유일해야 하기 때문에 허용되지 않는다:
수정했습니다.

2017-12-15 02:30 UTC, voidsatisfaction commented on Types/struct_types.md
> +	T     // 임베드된 필드 *T, *P.T와 충돌
수정했습니다.

2017-12-15 04:02 UTC, voidsatisfaction commented on Types/struct_types.md
> +구조체 `x`에 임베드된 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html) `f`는 `x.f`가 필드 혹은 [메서드](/Declarations%20and%20scope/method_declarations.html)를 의미하는 유효한 [selector](/Expressions/selecto
수정했습니다. 참고 링크 감사합니다.

2017-12-15 04:02 UTC, voidsatisfaction commented on Types/struct_types.md
> +promoted 필드는 구조체의 [합성 리터럴](/Expressions/composite_literals.html)에서 필드 이름으로 사용 될 수 없는 것을 제외하고 일반적인 필드 처럼 행동한다.
수정했습니다.

2017-12-15 04:34 UTC, voidsatisfaction commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `T`를 표함하면, `S`와 `*S`의 [메서드 집합](/Types/method_sets.html)은 receiver `T`와 함께 promoted 메서드를 포함한다. `*S`의 메서드 셋 역시 receiver `T`와 함께 promoted 메서드를 포함한다.
수정했습니다.

2017-12-15 04:34 UTC, voidsatisfaction commented on Types/struct_types.md
> +  * 만약 `S`가 임베드된 필드 `*T`를 포함하면, `S`와 `*S`의 메서드 집합은 receiver `T`,`*T`와 함께 promoted 메서드를 포함한다.
수정했습니다.

2017-12-15 04:37 UTC, voidsatisfaction commented on Types/struct_types.md
> +필드 선언에 문자열 리터럴 *태그* 를 선택적으로 놓을 수 있다. 그리고 그 태그는 해당하는 필드 선언의 모든 필드를 위한 속성이 된다. 공백의 태그 문자열은 태그가 없는 것과 같다. 태그들은 [reflection interface](https://golang.org/pkg/reflect/#StructTag)를 통해서 볼 수 있고, 구조체의 [타입 식별자
수정했습니다.

2017-12-15 04:39 UTC, voidsatisfaction commented on Types/struct_types.md
> +	x, y float64 ""  // 공백 태그 문자열은 태그가 없는 것과 같다.
수정했습니다.

2017-12-15 04:40 UTC, voidsatisfaction commented on Types/struct_types.md
> +// TimeStamp protocol buffer와 대응하는 구조체.
수정했습니다.

2017-12-15 04:40 UTC, voidsatisfaction commented on Types/struct_types.md
> +// reflect 패키지에 의해 구체화된 관습을 따른다.
수정했습니다.

2017-12-18 01:35 UTC, dakeshi approved these changes

2017-12-18 01:36 UTC, merged