Translate numeric_types
golangkorea/golang-spec pull request #153
Opened 2017-12-19 23:06 UTC by findstar

### 체크리스트
- [✔ ] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 
- [ ] 용어집에 추가할 번역 용어가 있나요? 있다면 [이슈 게시판](https://github.com/golangkorea/golang-spec/issues/105)에 코멘트를 남겨주세요.

### 설명
숫자 타입을 번역했습니다. 

### 참고사항(선택사항)
alias : 별칭
expression: 표현식

이라고 번역했는데. 적당한지 의견 부탁드립니다.

2017-12-20 00:43 UTC, jhonghee requested changes

2017-12-20 00:43 UTC, jhonghee commented on Types/numeric_types.md
> +*numeric 타입*은 정수 또는 부동 소수점 값 세트를 나타낸다. 아키텍처에 관계없이 미리 선언된 숫자 타입은 다음과 같:
다음과 같: => 다음과 같다:

2017-12-20 00:43 UTC, jhonghee commented on Types/numeric_types.md
> +int8        모든 부호가 존재하는  8비트 정수 (-128 to 127)
"부호 없는"으로 번역하셨으니까 "부호 있는"으로 번역하는게 좋지 않을까요?

2017-12-20 00:43 UTC, jhonghee commented on Types/numeric_types.md
> +complex64   float32의 모든 실수 및 허수의 복소수
모든 float32의 실수와 허수부분들을 갖는 복소수

2017-12-20 00:43 UTC, jhonghee commented on Types/numeric_types.md
> +*n*비트의 정수 값은 *n*비트의 폭을 가지며 [2의 보수 연산](http://en.wikipedia.org/wiki/Two's_complement)을 사용하여 표시된다.
*n*비트 => *n*-비트

represented using [two's complement arithmetic](http://en.wikipedia.org/wiki/Two's_complement) 는 연산을 의미하기 보다는 data representation을 의미하지 않을 까요? 그래서 그냥 => [2의 보수](http://en.wikipedia.org/wiki/Two's_complement)를 사용하여 나타낸다.

2017-12-20 00:43 UTC, jhonghee commented on Types/numeric_types.md
> +구현시 최적화된 사이즈를 가지는 미리 선언된 숫자 타입도 있다:
또 미리 선언된 숫자 타입에는 그 크기가 구현에 따라 달라지는 경우도 있다:

or

또 미리 선언된 숫자 타입중에는 구현시 다른 크기가 선택되는 경우도 있다.

2017-12-20 00:43 UTC, jhonghee commented on Types/numeric_types.md
> +이식성 문제를 회피하기 위해서 `unit8`의 별칭(alias)인 `byte`, `int32` 의 별칭(alias)인 `rune`을 제외한 모든 숫자 타입은 구분된다. 표현식(expression)이나 할당에서 다른 숫자 타입이 섞여 있다면, 변환을 필요로 한다. 예를 들어, `int32` 와 `int`는 특정 아키텍처에서 동일한 사이즈를 가질 수 있지만
`unit8`의 별칭(alias)인 `byte`, `int32` 의 별칭(alias)인 `rune`을 제외한 모든 숫자 타입들이 서로 구분되게 함으로써 이식성 문제를 피할 수 있다.

2017-12-20 00:55 UTC, jhonghee commented on Types/numeric_types.md
> +uintptr  포인트 값의 해석되지 않은 비트를 저장하는데 충분히 큰 부호가 없는 정수
포인터 값이면서 (아직 타입으로) 해석되지 않은 비트들를 저장할 만큼 크고, 부호가 없는 정수

2017-12-20 01:11 UTC, dakeshi requested changes
번역 수고하셨습니다.

2017-12-20 01:11 UTC, dakeshi commented on Types/numeric_types.md
> +*numeric 타입*은 정수 또는 부동 소수점 값 세트를 나타낸다. 아키텍처에 관계없이 미리 선언된 숫자 타입은 다음과 같:
> numeric 타입은 정수 또는 부동 소수점 값 세트를 나타낸다.

번역 가이드문서 4번 항목에 따라 `숫자 타입` 으로 번역해주시면 되고 `세트`의 경우 대부분의 챕터에서 `집합`이라는 용어로 번역하고 있는데 이 문장에서는 의역해도 될 것 같네요.

숫자 타입은 정수나 부동 소수점 값을 표현한다.

> 아키텍처에 관계없이 미리 선언된 숫자 타입은 다음과 같:

미리 선언된 숫자 타입 중 아키텍처 독립적인 숫자 타입은 다음과 같다:

2017-12-20 01:11 UTC, dakeshi commented on Types/numeric_types.md
> +uint8       모든 부호 없는  8비트 정수 (0 to 255)
`모든` 위치를 조정하는게 나을 듯. 아래 문장들도 마찬가지입니다.

부호 없는 모든 8비트 정수

2017-12-20 01:11 UTC, dakeshi commented on Types/numeric_types.md
> +complex64   float32의 모든 실수 및 허수의 복소수
float32의 실수와 허수로 구성된 모든 복소수

2017-12-20 01:11 UTC, dakeshi commented on Types/numeric_types.md
> +*n*비트의 정수 값은 *n*비트의 폭을 가지며 [2의 보수 연산](http://en.wikipedia.org/wiki/Two's_complement)을 사용하여 표시된다.
연산은 operation이 가까울 것 같습니다.

2의 보수 산술

2017-12-20 01:11 UTC, dakeshi commented on Types/numeric_types.md
> +구현시 최적화된 사이즈를 가지는 미리 선언된 숫자 타입도 있다:
또 미리 선언된 숫자 타입 중 구현에 따라 그 크기가 달라지는 경우도 있다:

2017-12-20 01:11 UTC, dakeshi commented on Types/numeric_types.md
> +uintptr  포인트 값의 해석되지 않은 비트를 저장하는데 충분히 큰 부호가 없는 정수
포인터 값 중 해석되지 않는 비트를 저장할 수 있을 정도로 충분히 큰 부호 없는 정수

2017-12-20 01:11 UTC, dakeshi commented on Types/numeric_types.md
> +이식성 문제를 회피하기 위해서 `unit8`의 별칭(alias)인 `byte`, `int32` 의 별칭(alias)인 `rune`을 제외한 모든 숫자 타입은 구분된다. 표현식(expression)이나 할당에서 다른 숫자 타입이 섞여 있다면, 변환을 필요로 한다. 예를 들어, `int32` 와 `int`는 특정 아키텍처에서 동일한 사이즈를 가질 수 있지만
> 이식성 문제를 회피하기 위해서 `unit8`의 별칭(alias)인 `byte`, `int32` 의 별칭(alias)인 `rune`을 제외한 모든 숫자 타입은 구분된다.

`unit8`의 별칭(alias)인 `byte`, `int32` 의 별칭(alias)인 `rune`을 제외한 모든 숫자 타입이 서로 다르기 때문에 이식성(portability) 문제를 피할 수 있다.

> 표현식(expression)이나 할당에서 다른 숫자 타입이 섞여 있다면, 변환을 필요로 한다.

용어집에서 index expression 은 `인덱스 표현`으로 추가되어 있고 expression 챕터에 속한 내용들을 표현하기 위해서도 `표현`으로 번역하는 것이 가장 적당할 것 같습니다. 

표현(expression)이나 할당에 서로 다른 숫자 타입이 함께 사용된 경우, 변환(conversion)이 필요하다.

> 예를 들어, `int32` 와 `int`는 특정 아키텍처에서 동일한 사이즈를 가질 수 있지만 동일한 타입이 아니다.

예를 들어, `int32` 와 `int`가 특정 아키텍처 환경에서는 같은 크기일 수 있지만 같은 타입은 아니다.

2017-12-26 00:04 UTC, dakeshi approved these changes

2017-12-26 00:05 UTC, merged

2017-12-26 00:06 UTC, dakeshi commented
@findstar 수고하셨습니다. 👍   italic 문법 수정하고 "세트"를 "집합"으로 수정한 뒤 merge 처리했습니다.