여러 인자를 ...매개변수로 넘기기 번역
golangkorea/golang-spec pull request #160
Opened 2017-12-22 08:08 UTC by ezaurum

### 체크리스트
- [x] [번역 가이드 라인](https://github.com/golangkorea/golang-spec#번역-가이드라인) 문서는 읽어보셨나요? 
- [x] 용어집에 추가할 번역 용어가 있나요? 있다면 [이슈 게시판](https://github.com/golangkorea/golang-spec/issues/105)에 코멘트를 남겨주세요.

### 설명

### 참고사항(선택사항)

2017-12-26 07:36 UTC, dakeshi requested changes
번역 수고하셨습니다 👍  underlying array는 내재 배열로 번역했습니다.

2017-12-26 07:36 UTC, dakeshi commented on Expressions/passing_arguments_to__parameters.md
> +# [여러 인자를 ...매개변수로 넘기기(Passing arguments to ... parameters)](#passing-arguments-to-parameters) {#passing-arguements-to-parameters}
syntax 수정이 필요해보입니다.

기존 reference id 표현 방식으로는 `...`을 추가할 수도 없고, title과 다른 reference id를 부여할 수 없기 때문에 [gitbook에서 허용하는 reference id 포맷 규칙](https://toolchain.gitbook.com/syntax/markdown.html)에 따라 reference id를 작성해야 한다고 안내드렸습니다.
```
 # test new tag {#new-tag}
```
따라서 아래와 같이 표현하시면 될 것 같습니다.

```
# 여러 인자를 ...매개변수로 넘기기(Passing arguments to ... parameters) {#passing-arguements-to-parameters}
```

2017-12-26 07:36 UTC, dakeshi commented on Expressions/passing_arguments_to__parameters.md
> +주어진 함수를 다음과 같이 호출하면,
> 주어진 함수를 다음과 같이 호출하면,

의역하는 것이 좋을 것 같습니다.

`Greeting` 함수를 다음과 같이 호출했을때,

2017-12-26 07:36 UTC, dakeshi commented on Expressions/passing_arguments_to__parameters.md
> +만일 `f`가 마지막 매개변수 `p`의 타입이 `...T`인 [가변 인자 함수](/Types/function_types.html)라면, `f` 안에서 `p`의 타입은 `[]T` 타입과 동일하다. 만일 `f`가 `p`에 해당하는 인자 없이 호출된다면, `p`에 `nil`값이 들어간다. 인자가 있는 경우, `[]T` 타입의 새 슬라이스가 넘겨진다. 슬라이스에
> 만일 `f`가 마지막 매개변수 `p`의 타입이 `...T`인 [가변 인자 함수](/Types/function_types.html)라면, `f` 안에서 `p`의 타입은 `[]T` 타입과 동일하다.

마지막 매개변수 `p`가 `...T` 타입인 가변 인자 함수 `f`의  내부에서는 매개변수 `p`의 타입이 `[]T`와 같다.

> 만일 `f`가 `p`에 해당하는 인자 없이 호출된다면, `p`에 `nil`값이 들어간다. 

함수 `f` 호출시 매개변수 `p`에 해당하는 인자들이 없다면, 매개변수 `p`에는 `nil` 값이 전달된다. 

> 인자가 있는 경우, `[]T` 타입의 새 슬라이스가 넘겨진다. 슬라이스에 내재된 배열은 실제 인자와 같은 값을 가지는데, 각 인자는 모두 T에 [할당 가능](/Properties%20of%20types%20and%20values/assignability.html) 해야 한다.

T에 코드 태그가 빠졌고 new array에 대한 내용도 언급하면 좋겠네요.

인자가 있는 경우, 매개변수 `p`에는 새로운 내재 배열(underling array)이 함께하는 `[]T` 타입의 새로운 슬라이스가 전달된다. 이 내재 배열의 요소들은 매개변수 `p`에 전달되는 실제 인자들로 구성되며 모든 인자들은 `T`에 할당할 수 있어야 한다.

> 각 호출시점에 `p`에 할당된 인자의 수에 따라 슬라이스의 길이와 캐퍼시티가 달라진다.

length는 `길이`, capacity는 `용량`으로 번역하고 있습니다.

슬라이스의 길이와 용량(capacity)은 각 호출 시점에 매개변수 `p`에 할당된 인자의 수에 따라 달라진다.

2017-12-26 07:36 UTC, dakeshi commented on Expressions/passing_arguments_to__parameters.md
> +`Greeting` 안에서 `who`는 첫 번째 호출에는 `nil`이고, 두 번째에는 `[]string{"Joe", "Anna", "Eileen"}`가 된다.
> `Greeting` 안에서 `who`는 첫 번째 호출에는 `nil`이고, 두 번째에는 `[]string{"Joe", "Anna", "Eileen"}`가 된다.

`Greeting` 함수 안에서 `who`는 첫 번째 호출에서는 `nil` 값을, 두 번째 호출때는 `[]string{"Joe", "Anna", "Eileen"}`값을 갖는다.

2017-12-26 07:36 UTC, dakeshi commented on Expressions/passing_arguments_to__parameters.md
> +마지막 인자가 타입 `[]T`의 슬라이스에 할당가능하면, 인자 뒤에 ...을 붙여서 ...T 매개변수의 값으로 그대로 넘길 수 있다. 이 경우 새 슬라이스가 생기지 않는다.
> 마지막 인자가 타입 `[]T`의 슬라이스에 할당가능하면, 인자 뒤에 ...을 붙여서 ...T 매개변수의 값으로 그대로 넘길 수 있다. 이 경우 새 슬라이스가 생기지 않는다.

마지막 인자를 슬라이스 타입 `[]T`에 할당할 수 있다면, 인자 뒤에 `...`을 붙여서 이 인자를 그대로 `...T` 매개변수에 대한 값으로 전달할 수 있다. 이 경우에는 새로운 슬라이스가 생성되지 않는다.

2017-12-26 07:36 UTC, dakeshi commented on Expressions/passing_arguments_to__parameters.md
> +주어진 슬라이스 `s`를 이용해서 다음과 같이 호출하면,
슬라이스 `s`에 대해 다음과 같이 호출했을때,

2017-12-26 07:36 UTC, dakeshi commented on Expressions/passing_arguments_to__parameters.md
> +`Greeting` 안에서 `who`는 s와 같은 값으로 같은 내재된 배열을 갖게 된다.
`Greeting` 함수 안에서 `who`는 `s` 와 같은 값을 가질 것이고,  내재 배열도 `s`와 같을 것이다.

2017-12-26 14:46 UTC, ezaurum commented on Expressions/passing_arguments_to__parameters.md
> +만일 `f`가 마지막 매개변수 `p`의 타입이 `...T`인 [가변 인자 함수](/Types/function_types.html)라면, `f` 안에서 `p`의 타입은 `[]T` 타입과 동일하다. 만일 `f`가 `p`에 해당하는 인자 없이 호출된다면, `p`에 `nil`값이 들어간다. 인자가 있는 경우, `[]T` 타입의 새 슬라이스가 넘겨진다. 슬라이스에
> 슬라이스에 내재된 배열은 새로 생성되고, 실제 인자와 같은 값을 가지므로, 각 인자는 모두 T에 할당가능 해야 한다.
로 변경했습니다.

2017-12-27 05:09 UTC, dakeshi approved these changes

2017-12-27 05:09 UTC, merged