세미콜론 번역
golangkorea/golang-spec pull request #27
Opened 2017-11-30 07:10 UTC by ezaurum

세미콜론 꼭치 번역 추가

2017-11-30 08:46 UTC, dakeshi requested changes
번역 감사드립니다.  일단은 약간만 수정하면 될 듯 합니다. 마지막 문단은 한번 더 읽어봐야 겠네요.

2017-11-30 08:46 UTC, dakeshi commented on Lexical elements/semicolons.md
> +spec 버전: of June 28, 2017
> spec 버전: of June 28, 2017

spec, 원문, 번역자 앞에 아래와 같이 unordered list 포맷을 적용해 주세요.

\* spec 버전: of June 28, 2017

2017-11-30 08:46 UTC, dakeshi commented on Lexical elements/semicolons.md
> +많은 언어에서 세미콜론 ";" 을 종결자로 사용하는 것이 공식적인 문법이다. Go 프로그램은 다음 두 가지 규칙 아래 대부분의 세미콜론을 생략할 수 있다.
> 많은 언어에서 세미콜론 ";" 을 종결자로 사용하는 것이 공식적인 문법이다.

아래와 같은 해석은 어떨까요?
많은 언어에서 세미콜론 ";" 은 주로 종결자로 사용한다.

2017-11-30 15:34 UTC, ezaurum commented on Lexical elements/semicolons.md
> +많은 언어에서 세미콜론 ";" 을 종결자로 사용하는 것이 공식적인 문법이다. Go 프로그램은 다음 두 가지 규칙 아래 대부분의 세미콜론을 생략할 수 있다.
> 많은 언어에서 세미콜론 ";" 은 주로 종결자로 사용한다. Go 프로그램은 다음 두 가지 규칙 아래 대부분의 세미콜론을 생략할 수 있다.

그렇게 되면 다음 문장과의 관계성을 고려할 때, 종결자 이외의 다른 용도로 사용된다는 해석이 될 듯 합니다.

> 많은 언어에서 세미콜론 ";" 을 종결자로 사용하는 것이 공식적인 문법이다. (하지만) Go 프로그램은 다음 두 가지 규칙 아래 대부분의 세미콜론을 생략할 수 있다.

"하지만"이 생략되어서 세미콜론을 종결자로 사용하는 것이 공식적인 문법이지만, Go 언어에서는 생략할 수 있다는 의미가 합당할 듯 합니다.

2017-11-30 15:35 UTC, ezaurum commented on Lexical elements/semicolons.md
> +spec 버전: of June 28, 2017
네 수정했습니다.

2017-11-30 23:27 UTC, dakeshi approved these changes

2017-11-30 23:28 UTC, merged

2017-12-01 00:25 UTC, dakeshi commented
수정 감사합니다.