문자열 고정값 번역
golangkorea/golang-spec pull request #97
Opened 2017-12-05 06:32 UTC by ezaurum

문자열 고정값 꼭지 번역

2017-12-05 06:44 UTC, dakeshi requested changes

2017-12-05 06:44 UTC, dakeshi commented on Lexical elements/string_literals.md
> +# 문자열 고정값
section header 참조를 위해 번역 가이드가 약간 변경되었습니다.

```
# [문자열 고정값(String literals)](#string-literals)
```
으로 수정부탁드립니다.

2017-12-05 06:44 UTC, dakeshi commented on Lexical elements/string_literals.md
> + * spec 버전: June 28, 2017
spec 버전에서 Go 버전을 사용하는 것으로 번역 가이드 변경되었습니다.

```
* Go 버전: 1.9
```

2017-12-05 06:44 UTC, dakeshi commented on Lexical elements/string_literals.md
> +<a id="string_lit">문자열 고정값</a>             = <a href="#raw_string_lit">비가공 문자열 고정값</a> | <a href="#interpreted_string_lit">가공 문자열 고정값</a> .
문법 표현은 우선 번역하지 않고 영문을 유지해주시기 바랍니다. 문법 표현에 사용된 주석은 번역 가능합니다. 이와 관련해서는 조만간 번역 가이드 업데이트하겠습니다.

2017-12-05 06:45 UTC, dakeshi commented on Lexical elements/string_literals.md
> +# 문자열 고정값
상단에 영문 header는 삭제하시고 한 줄에서 한글/영문/reference id 로 section header 구성 바랍니다.

2017-12-07 10:06 UTC, ezaurum commented
가이드라인 맞추어 수정했습니다.

2017-12-08 00:37 UTC, jhonghee commented on Lexical elements/string_literals.md
> +만일 소스코드가 강세표와 한 영문자를 포함하는 형태 같이 두 개 코드값을 하나의 문자에 넣으려고 한다면, 룬 리터럴에 넣을 때는 하나의 코드값이 아니므로 에러가 나고, 문자열 리터럴에 넣을 때는 두 개 코드값으로 나타날 것이다.
code point는 glossary에 코드 포인트로 되어 있네요.

2017-12-08 00:38 UTC, jhonghee approved these changes

2017-12-08 17:15 UTC, ezaurum commented
code point는 코드 포인트로 수정했습니다.

2017-12-11 09:07 UTC, dakeshi approved these changes

2017-12-12 01:02 UTC, merged